<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'id' => 1,
                'category_id' => 1,
                'code' => 'AFT-ELC-001',
                'name' => 'Laptop ASUS Vivobook',
                'stock' => 10,
                'location' => 'Ruang Staf Lantai 2',
                'condition' => 'Bagus',
                'image' => 'products/qGZ0czC0z1Ef6gqai2p3Loj2JtrGUg2sznEZIfIo.png',
                'created_at' => '2026-07-05 13:45:50',
                'updated_at' => '2026-07-05 06:47:26',
            ],
            [
                'id' => 2,
                'category_id' => 1,
                'code' => 'AFT-ELC-002',
                'name' => 'Projector Epson',
                'stock' => 5,
                'location' => 'Ruang Rapat Utama',
                'condition' => 'Bagus',
                'image' => 'products/mS5gCSLYoFl0w6ybN6nafp7QAW0Y9LQeeqVRh7nX.png',
                'created_at' => '2026-07-05 13:45:50',
                'updated_at' => '2026-07-05 06:54:58',
            ],
            [
                'id' => 3,
                'category_id' => 1,
                'code' => 'AFT-ELC-003',
                'name' => 'Printer Canon Pixma',
                'stock' => 4,
                'location' => 'Ruang Administrasi',
                'condition' => 'Bagus',
                'image' => 'products/RLgSFOOtkBT9aGgrfiKUJdsB98UKU3K1ONEpw66h.png',
                'created_at' => '2026-07-05 13:45:50',
                'updated_at' => '2026-07-08 05:58:00',
            ],
            [
                'id' => 4,
                'category_id' => 1,
                'code' => 'AFT-ELC-004',
                'name' => 'Mouse Wireless Logitech',
                'stock' => 15,
                'location' => 'Gudang Inventaris',
                'condition' => 'Bagus',
                'image' => 'products/UYrAHinu8JIHGafGNprqHdoyupwaAq5XsGqbkIBx.png',
                'created_at' => '2026-07-05 13:45:50',
                'updated_at' => '2026-07-05 07:00:44',
            ],
            [
                'id' => 5,
                'category_id' => 1,
                'code' => 'AFT-ELC-005',
                'name' => 'Keyboard Logitech',
                'stock' => 12,
                'location' => 'Gudang Inventaris',
                'condition' => 'Bagus',
                'image' => 'products/XVdKJtC8Lnb7pRFCNrivJ1Hkf7UnPfdJSAVIGGS0.png',
                'created_at' => '2026-07-05 13:45:50',
                'updated_at' => '2026-07-07 22:27:00',
            ],
            [
                'id' => 6,
                'category_id' => 2,
                'code' => 'AFT-ATK-001',
                'name' => 'Papan Tulis Whiteboard',
                'stock' => 6,
                'location' => 'Ruang Kelas 1',
                'condition' => 'Rusak Ringan',
                'image' => 'products/7l2FzMmBT6pLW7dSqYPXzFIXqi6jtKz9Bu2eeArL.png',
                'created_at' => '2026-07-05 13:45:50',
                'updated_at' => '2026-07-07 22:30:20',
            ],
            [
                'id' => 7,
                'category_id' => 2,
                'code' => 'AFT-ATK-002',
                'name' => 'Paper Shredder Penghancur Kertas',
                'stock' => 3,
                'location' => 'Ruang Arsip',
                'condition' => 'Bagus',
                'image' => 'products/rXJH0jgVv7oLav2tDfC1qSuCFeGy693FUz6ZFxbh.png',
                'created_at' => '2026-07-05 13:45:50',
                'updated_at' => '2026-07-07 22:29:54',
            ],
            [
                'id' => 8,
                'category_id' => 2,
                'code' => 'AFT-ATK-003',
                'name' => 'Stapler Besar Kangaro',
                'stock' => 8,
                'location' => 'Meja Resepsionis',
                'condition' => 'Bagus',
                'image' => 'products/hEkz1eKwoXc8nYiBNxVoBMys3fC5JcIuE3gsOXcJ.png',
                'created_at' => '2026-07-05 13:45:50',
                'updated_at' => '2026-07-07 22:30:38',
            ],
            [
                'id' => 9,
                'category_id' => 2,
                'code' => 'AFT-ATK-004',
                'name' => 'Pemotong Kertas Paper Cutter',
                'stock' => 4,
                'location' => 'Ruang Administrasi',
                'condition' => 'Bagus',
                'image' => 'products/diKzJ5vdCw9iIVuPMN3mKnV6yu4ozUY7ZF9ejkb5.png',
                'created_at' => '2026-07-05 13:45:50',
                'updated_at' => '2026-07-07 22:30:54',
            ],
            [
                'id' => 10,
                'category_id' => 3,
                'code' => 'AFT-FAS-001',
                'name' => 'Kursi Kerja Kantor Roda',
                'stock' => 25,
                'location' => 'Ruang Kerja Utama',
                'condition' => 'Rusak Berat',
                'image' => 'products/NmiclUHEOop7rEvx8iWXDnVUAtMmVwRMsyIt7U0X.png',
                'created_at' => '2026-07-05 13:45:50',
                'updated_at' => '2026-07-08 05:47:03',
            ],
            [
                'id' => 11,
                'category_id' => 3,
                'code' => 'AFT-FAS-002',
                'name' => 'Meja Kayu Kerja',
                'stock' => 7,
                'location' => 'Ruang Kerja Utama',
                'condition' => 'Rusak Berat',
                'image' => 'products/K42ZFts2fxSgMQh2e7NeSQw22OUqt11eyXLEe0Sg.png',
                'created_at' => '2026-07-05 13:45:50',
                'updated_at' => '2026-07-08 05:58:00',
            ],
            [
                'id' => 12,
                'category_id' => 3,
                'code' => 'AFT-FAS-003',
                'name' => 'Dispenser Air Sharp',
                'stock' => 3,
                'location' => 'Pantry Lantai 2',
                'condition' => 'Rusak Ringan',
                'image' => 'products/Il6O3kHFA8S1LbqMh1QLDHZegL8VcQTivX9hLIsu.png',
                'created_at' => '2026-07-05 13:45:50',
                'updated_at' => '2026-07-07 22:33:56',
            ],
            [
                'id' => 13,
                'category_id' => 3,
                'code' => 'AFT-FAS-004',
                'name' => 'Kipas Angin Berdiri Cosmos',
                'stock' => 5,
                'location' => 'Ruang Tamu',
                'condition' => 'Bagus',
                'image' => 'products/st0YhixOa50RwLelKvpVCbMATntw9qbUuXVqTpZv.png',
                'created_at' => '2026-07-05 13:45:50',
                'updated_at' => '2026-07-07 22:34:11',
            ],
        ];

        foreach ($products as $product) {
            DB::table('products')->updateOrInsert(['id' => $product['id']], $product);
        }
    }
}
